import tempfile
from pathlib import Path

from typer.testing import CliRunner

from brain.cli import app

runner = CliRunner()


def _run_with_config(config_text: str, args: list[str]):
    with tempfile.TemporaryDirectory() as tmpdir:
        config_path = Path(tmpdir) / "config.toml"
        config_path.write_text(config_text)

        import brain.config as config_mod

        orig_default = config_mod.DEFAULT_CONFIG_PATH
        config_mod.DEFAULT_CONFIG_PATH = config_path
        try:
            return runner.invoke(app, args)
        finally:
            config_mod.DEFAULT_CONFIG_PATH = orig_default


def test_echo_e2e():
    result = _run_with_config(
        """
ollama_url = "http://localhost:11434"

[[routines]]
name = "test-echo"
action = "echo"
trigger = { type = "manual" }
params = { message = "hello from e2e" }
""",
        ["routine", "run", "test-echo"],
    )
    assert result.exit_code == 0, result.output
    assert "succeeded" in result.output
    assert "hello from e2e" in result.output


def test_shell_e2e():
    with tempfile.TemporaryDirectory() as tmpdir:
        marker = Path(tmpdir) / "shell-ran.txt"
        result = _run_with_config(
            f"""
ollama_url = "http://localhost:11434"

[[routines]]
name = "test-shell"
action = "shell"
trigger = {{ type = "manual" }}
params = {{ command = "echo shell-works > {marker}", timeout = 10 }}
""",
            ["routine", "run", "test-shell"],
        )
        assert result.exit_code == 0, result.output
        assert "succeeded" in result.output
        assert marker.exists()
        assert "shell-works" in marker.read_text()


def test_pdf_export_e2e():
    with tempfile.TemporaryDirectory() as tmpdir:
        pdf_path = Path(tmpdir) / "test.pdf"
        result = _run_with_config(
            f"""
ollama_url = "http://localhost:11434"

[[routines]]
name = "test-pdf"
action = "pdf_export"
trigger = {{ type = "manual" }}
params = {{ output_path = "{pdf_path}", title = "E2E Test", body = "This PDF was generated by a routine." }}
""",
            ["routine", "run", "test-pdf"],
        )
        assert result.exit_code == 0, result.output
        assert "PDF written to" in result.output
        assert pdf_path.exists()
        assert pdf_path.stat().st_size > 0


def test_pdf_export_with_query_e2e():
    """PDF export uses plain formatting when query results are appended."""
    with tempfile.TemporaryDirectory() as tmpdir:
        pdf_path = Path(tmpdir) / "test-query.pdf"
        result = _run_with_config(
            f"""
ollama_url = "http://localhost:11434"

[[routines]]
name = "test-pdf-query"
action = "pdf_export"
trigger = {{ type = "manual" }}
params = {{ output_path = "{pdf_path}", title = "Query Test", body = "Results:" }}
""",
            ["routine", "run", "test-pdf-query"],
        )
        assert result.exit_code == 0, result.output
        assert pdf_path.exists()
        assert pdf_path.stat().st_size > 0
